a, b, c = input().split(" ")
a = float(a)
b = float(b)
c = float(c)
tringulo = float((a * c) / 2)
circulo = float(3.14159 * c * c)
trapezio = float(((a + b) * c) / 2)
quadrado = float(b * b)
retangulo = a * b
print("TRIANGULO: %.3f" %(tringulo))
print("CIRCULO: %.3f" %(circulo))
print("TRAPEZIO: %.3f" %(trapezio))
print("QUADRADO: %.3f" %(quadrado))
print("RETANGULO: %.3f" %(retangulo))